# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: biprateep@pitt.edu
author_name: Biprateep Dey
create_example_module: true
custom_install: true
enforce_style:
- pylint
- black
- isort
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: calpit
project_license: MIT
project_name: calpit
project_organization: lee-group-cmu
python_versions:
- '3.10'
- '3.11'
- '3.12'
